#
# Recommend use for static configuration that does not change between environments.
#
# See also config/application.properties
#
isis:

  applib:
    annotation:
      action:
        explicit: true

  core:
    meta-model:
      validator:
        allow-deprecated: false
        no-params-only: true
        explicit-object-type: true

  viewer:
    wicket:
      application:
        about: Hello World
        brand-logo-header: images/apache-isis/logo-48x48.png
        css: css/application.css
        favicon-url: images/favicon.png
        js: scripts/application.js
        menubars-layout-xml: menubars.layout.xml
        name: Hello World App

      credit:
        - url:  http://isis.apache.org
          image: images/apache-isis/logo-48x48.png
          name: Apache Isis

      themes:
        show-chooser: true

      bookmarked-pages:
        show-chooser: true
        show-drop-down-on-footer: true

      max-title-length-in-standalone-tables: 0
      max-title-length-in-parented-tables: 0

  persistence:
    schema:
      auto-create-schemas: hello
      create-schema-sql-template: "CREATE SCHEMA IF NOT EXISTS %S"

eclipselink:
  # if enabled, then must be run with JVM arg:
  # -javaagent:lib/spring-instrument-5.3.5.jar
  weaving: false
  # if weaving subproperties are required, then specify all eclipselink.weaving
  # properties using application.properties instead (it's not possible to
  # specify both eclipselink.weaving property and its subsproperties using yaml syntax)

resteasy:
  jaxrs:
    app:
      registration: beans
    defaultPath: "/restful"

server:
  max-http-header-size: 16KB

spring:
  banner:
    location: banner.txt

